エラーを確認してもらうためpush
zero2hero-jp/SecBokApp-server pull request #32
Opened 2022-11-23 00:23 UTC by yuukii125

[こちらの件](https://zero-2-hero.slack.com/archives/C04BACSTSNM/p1669127459336879)でひとまずdraftであげています

2022-11-24 14:48 UTC, yuukii125 commented
[こちら](https://zero-2-hero.slack.com/archives/C04BACSTSNM/p1669269358535599?thread_ts=1669129117.337739&cid=C04BACSTSNM)の件で動作確認ができ次第、レビューお願いします。

2022-11-25 01:12 UTC, tatsuro1997 requested changes
Dockerfileだけ確認お願いします。

2022-11-25 01:12 UTC, tatsuro1997 commented on Dockerfile
> +  apk add --no-cache libc6-compat gcompat
Dockerfileに追記いただいた部分は[こちら](https://github.com/zero2hero-jp/SecBokApp-server/issues/34)のissueにあるように対応していただきたいです。

なのでこのPRにはDockerfileは含めないように願いします。

2022-11-25 17:09 UTC, yuukii125 commented on Dockerfile
> +  apk add --no-cache libc6-compat gcompat
承知しました！

2022-11-28 01:05 UTC, tatsuro1997 approved these changes

2022-11-29 09:34 UTC, yokohama requested changes

2022-11-29 09:34 UTC, yokohama commented on spec/factories/sheets.rb
> +    sequence(:email) { |n| "test#{n}@example.com" }
ありがちなのですが、exampel.comは実際にあるドメインなので、実際にメールが飛んだりしないように、自社のドメインを使用するように心掛けて下さい。

今回は、「@zero2hero.jp」でお願いしますm(_ _)m

2022-11-29 10:58 UTC, yuukii125 commented on spec/factories/sheets.rb
> +    sequence(:email) { |n| "test#{n}@example.com" }
@yokohama 
ドメイン変更しましたので、ご確認お願いします！

2022-12-02 04:20 UTC, yokohama approved these changes

2022-12-02 14:12 UTC, merged