DockerをM1macに対応したものに変更する
zero2hero-jp/SecBokApp-server pull request #35
Opened 2022-11-25 17:23 UTC by yuukii125

## 該当チケット
#34 

## やったこと
M1 macが動作するようDockerfileを変更

## 動作確認
起動することを確認

2022-11-28 01:07 UTC, tatsuro1997 requested changes
issueがわかりづらくてすみません！

2022-11-28 01:07 UTC, tatsuro1997 commented on Dockerfile
> +  apk add --no-cache libc6-compat gcompat
>Dockerfile内でM1のときのみ処理が動作するようにしてください。

M1macのときのみ動作するようにしていただきたいです！

2022-11-28 08:31 UTC, yuukii125 commented on Dockerfile
> +  apk add --no-cache libc6-compat gcompat
すみません。勘違いしていました。
方向性の確認なんですか、「M1macだったら実行する」という分岐処理を行うイメージですか？

2022-11-28 09:23 UTC, yokohama commented on Dockerfile
> +  apk add --no-cache libc6-compat gcompat
@tatsuro1997 M1で作成されたGemfile.lockは、他のCPUに影響を与えないかチェックできてますか。確認お願いします。

2022-11-28 10:22 UTC, tatsuro1997 commented on Dockerfile
> +  apk add --no-cache libc6-compat gcompat
@yuukii125 
>「M1macだったら実行する」という分岐処理を行うイメージですか？

はい、その通りです！

2022-11-29 10:36 UTC, tatsuro1997 approved these changes

2022-11-29 10:51 UTC, yokohama approved these changes

2022-11-29 10:59 UTC, yuukii125 commented
マージします！

2022-11-29 10:59 UTC, merged